version: '2'
services:
  db:
    image: mrlesmithjr/mysql:latest
    volumes:
      - "db:/var/lib/mysql"
    ports:
      - "33306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "powerdns"
      MYSQL_DATABASE: "powerdns"
      MYSQL_USER: "powerdns"
      MYSQL_PASSWORD: "powerdns"

  pdns_authorative:
    depends_on:
      - db
      - pdns_recursor
    build: ./Authoritative
    image: docker-powerdns-authorative
    links:
      - db
      - pdns_recursor
    ports:
      - "53:53/udp"
      - "8081:8081"
    restart: always
    environment:
      PDNS_ALLOW_DDNS_UPDATE: "yes"
      PDNS_ALLOW_DDNS_UPDATE_FROM: "0.0.0.0/0"
      PDNS_API_KEY: "changeme"
      PDNS_GMYSQL_DBNAME: "powerdns"
      PDNS_GMYSQL_HOST: "db"
      PDNS_GMYSQL_PASSWORD: "powerdns"
      PDNS_GMYSQL_USER: "powerdns"
      PDNS_JSON_INTERFACE: "yes"
      PDNS_RECURSOR_SERVER: "pdns_recursor"
      PDNS_WEBSERVER_ADDRESS: "0.0.0.0"
      PDNS_WEBSERVER_PASSWORD: "changeme"
      PDNS_WEBSERVER_PORT: "8081"
      PDNS_WEBSERVER: "yes"
  pdns_recursor:
    build: ./Recursor
    image: docker-powerdns-recursor
    restart: always

volumes:
  db:
